version: 1.5.2
apkFileName: DevelopmentSettings.apk
isFrameworkApk: false
usesFramework:
  ids:
  - 1
sdkInfo:
  minSdkVersion: '14'
  targetSdkVersion: '17'
packageInfo:
  cur_package: com.android.development_settings
  orig_package: com.android.development_settings
compressionType: false
